/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as WhoAmIIndexImport } from './routes/who-am-i/index'
import { Route as WhatHaveIDoneIndexImport } from './routes/what-have-i-done/index'
import { Route as WhatDoIKnowIndexImport } from './routes/what-do-i-know/index'
import { Route as HowDoIContactIndexImport } from './routes/how-do-i-contact/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const WhoAmIIndexRoute = WhoAmIIndexImport.update({
  id: '/who-am-i/',
  path: '/who-am-i/',
  getParentRoute: () => rootRoute,
} as any)

const WhatHaveIDoneIndexRoute = WhatHaveIDoneIndexImport.update({
  id: '/what-have-i-done/',
  path: '/what-have-i-done/',
  getParentRoute: () => rootRoute,
} as any)

const WhatDoIKnowIndexRoute = WhatDoIKnowIndexImport.update({
  id: '/what-do-i-know/',
  path: '/what-do-i-know/',
  getParentRoute: () => rootRoute,
} as any)

const HowDoIContactIndexRoute = HowDoIContactIndexImport.update({
  id: '/how-do-i-contact/',
  path: '/how-do-i-contact/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/how-do-i-contact/': {
      id: '/how-do-i-contact/'
      path: '/how-do-i-contact'
      fullPath: '/how-do-i-contact'
      preLoaderRoute: typeof HowDoIContactIndexImport
      parentRoute: typeof rootRoute
    }
    '/what-do-i-know/': {
      id: '/what-do-i-know/'
      path: '/what-do-i-know'
      fullPath: '/what-do-i-know'
      preLoaderRoute: typeof WhatDoIKnowIndexImport
      parentRoute: typeof rootRoute
    }
    '/what-have-i-done/': {
      id: '/what-have-i-done/'
      path: '/what-have-i-done'
      fullPath: '/what-have-i-done'
      preLoaderRoute: typeof WhatHaveIDoneIndexImport
      parentRoute: typeof rootRoute
    }
    '/who-am-i/': {
      id: '/who-am-i/'
      path: '/who-am-i'
      fullPath: '/who-am-i'
      preLoaderRoute: typeof WhoAmIIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/how-do-i-contact': typeof HowDoIContactIndexRoute
  '/what-do-i-know': typeof WhatDoIKnowIndexRoute
  '/what-have-i-done': typeof WhatHaveIDoneIndexRoute
  '/who-am-i': typeof WhoAmIIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/how-do-i-contact': typeof HowDoIContactIndexRoute
  '/what-do-i-know': typeof WhatDoIKnowIndexRoute
  '/what-have-i-done': typeof WhatHaveIDoneIndexRoute
  '/who-am-i': typeof WhoAmIIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/how-do-i-contact/': typeof HowDoIContactIndexRoute
  '/what-do-i-know/': typeof WhatDoIKnowIndexRoute
  '/what-have-i-done/': typeof WhatHaveIDoneIndexRoute
  '/who-am-i/': typeof WhoAmIIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/how-do-i-contact'
    | '/what-do-i-know'
    | '/what-have-i-done'
    | '/who-am-i'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/how-do-i-contact'
    | '/what-do-i-know'
    | '/what-have-i-done'
    | '/who-am-i'
  id:
    | '__root__'
    | '/'
    | '/how-do-i-contact/'
    | '/what-do-i-know/'
    | '/what-have-i-done/'
    | '/who-am-i/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HowDoIContactIndexRoute: typeof HowDoIContactIndexRoute
  WhatDoIKnowIndexRoute: typeof WhatDoIKnowIndexRoute
  WhatHaveIDoneIndexRoute: typeof WhatHaveIDoneIndexRoute
  WhoAmIIndexRoute: typeof WhoAmIIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HowDoIContactIndexRoute: HowDoIContactIndexRoute,
  WhatDoIKnowIndexRoute: WhatDoIKnowIndexRoute,
  WhatHaveIDoneIndexRoute: WhatHaveIDoneIndexRoute,
  WhoAmIIndexRoute: WhoAmIIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/how-do-i-contact/",
        "/what-do-i-know/",
        "/what-have-i-done/",
        "/who-am-i/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/how-do-i-contact/": {
      "filePath": "how-do-i-contact/index.tsx"
    },
    "/what-do-i-know/": {
      "filePath": "what-do-i-know/index.tsx"
    },
    "/what-have-i-done/": {
      "filePath": "what-have-i-done/index.tsx"
    },
    "/who-am-i/": {
      "filePath": "who-am-i/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
